// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcaswvbbyecugvmeslmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjYXN3dmJieWVjdWd2bWVzbG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODk4NzcsImV4cCI6MjA2NzQ2NTg3N30.WoHZ0e0FDXFVV5tDuGViQnKz1GLTqNMVwdFwfnG8Q_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});